-- DropForeignKey
ALTER TABLE `RXNREL` DROP FOREIGN KEY `RXNREL_RXAUI1_fkey`;

-- DropForeignKey
ALTER TABLE `RXNREL` DROP FOREIGN KEY `RXNREL_RXAUI2_fkey`;

-- DropIndex
DROP INDEX `RXNREL_RXAUI1_idx` ON `RXNREL`;

-- DropIndex
DROP INDEX `RXNREL_RXAUI2_idx` ON `RXNREL`;

-- CreateIndex
CREATE INDEX `RXNREL_RXCUI1_idx` ON `RXNREL`(`RXCUI1`);

-- CreateIndex
CREATE INDEX `RXNREL_RXCUI2_idx` ON `RXNREL`(`RXCUI2`);
