version: '3.5'

name: rxnorm-explorer

# Services
services:
  mysql:
    container_name: rxnorm-explorer-db
    image: mysql
    ports:
      - ${DOCKER_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
    volumes:
      - './mysqldata:/var/lib/mysql'

# Volumes
volumes:
  mysqldata:
