SET FOREIGN_KEY_CHECKS=0;

-- AddForeignKey
ALTER TABLE `RXNREL` ADD CONSTRAINT `RXNREL_RXAUI1_fkey` FOREIGN KEY (`RXAUI1`) REFERENCES `RXNCONSO`(`RXAUI`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RXNREL` ADD CONSTRAINT `RXNREL_RXAUI2_fkey` FOREIGN KEY (`RXAUI2`) REFERENCES `RXNCONSO`(`RXAUI`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RXNSAT` ADD CONSTRAINT `RXNSAT_RXAUI_fkey` FOREIGN KEY (`RXAUI`) REFERENCES `RXNCONSO`(`RXAUI`) ON DELETE SET NULL ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;