-- CreateTable
CREATE TABLE `RXNCONSO` (
    `RXCUI` VARCHAR(8) NOT NULL,
    `LAT` VARCHAR(3) NOT NULL DEFAULT 'ENG',
    `TS` VARCHAR(1) NULL,
    `LUI` VARCHAR(8) NULL,
    `STT` VARCHAR(3) NULL,
    `SUI` VARCHAR(8) NULL,
    `ISPREF` VARCHAR(1) NULL,
    `RXAUI` VARCHAR(8) NOT NULL,
    `SAUI` VARCHAR(50) NULL,
    `SCUI` VARCHAR(50) NULL,
    `SDUI` VARCHAR(50) NULL,
    `SAB` VARCHAR(20) NOT NULL,
    `TTY` VARCHAR(20) NOT NULL,
    `CODE` VARCHAR(50) NOT NULL,
    `STR` VARCHAR(3000) NOT NULL,
    `SRL` VARCHAR(10) NULL,
    `SUPPRESS` VARCHAR(1) NULL,
    `CVF` VARCHAR(50) NULL,
    `id` INTEGER NOT NULL AUTO_INCREMENT,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RXNREL` (
    `RXCUI1` VARCHAR(8) NULL,
    `RXAUI1` VARCHAR(8) NULL,
    `STYPE1` VARCHAR(50) NULL,
    `REL` VARCHAR(4) NULL,
    `RXCUI2` VARCHAR(8) NULL,
    `RXAUI2` VARCHAR(8) NULL,
    `STYPE2` VARCHAR(50) NULL,
    `RELA` VARCHAR(100) NULL,
    `RUI` VARCHAR(10) NULL,
    `SRUI` VARCHAR(50) NULL,
    `SAB` VARCHAR(20) NOT NULL,
    `SL` VARCHAR(1000) NULL,
    `DIR` VARCHAR(1) NULL,
    `RG` VARCHAR(10) NULL,
    `SUPPRESS` VARCHAR(1) NULL,
    `CVF` VARCHAR(50) NULL,
    `id` INTEGER NOT NULL AUTO_INCREMENT,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RXNSAT` (
    `RXCUI` VARCHAR(8) NULL,
    `LUI` VARCHAR(8) NULL,
    `SUI` VARCHAR(8) NULL,
    `RXAUI` VARCHAR(8) NULL,
    `STYPE` VARCHAR(50) NULL,
    `CODE` VARCHAR(50) NULL,
    `ATUI` VARCHAR(11) NULL,
    `SATUI` VARCHAR(50) NULL,
    `ATN` VARCHAR(1000) NOT NULL,
    `SAB` VARCHAR(20) NOT NULL,
    `ATV` VARCHAR(4000) NULL,
    `SUPPRESS` VARCHAR(1) NULL,
    `CVF` VARCHAR(50) NULL,
    `id` INTEGER NOT NULL AUTO_INCREMENT,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

